- Client/Frontend/Browser/URLBarView.swift
> MOB-884 fix QR button margins

- Client/Frontend/Widgets/SiteTableViewController.swift
> MOB-889 fix crash by applying theme on UI layer

- Client/Frontend/Browser/SearchViewController.swift
removes the search engine customization on the search screen over the keyboard
> MOB-888 remove custom search in keyboard helper

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Browser/Tab.swift
> Synch tree counter

- Shared/AppInfo.swift
- Shared/UserAgent.swift
pretending to be FX 29.0 everywhere despite ecosia.org
> Hardcode FX Version to 29.0 for user agent

- Client/Assets/About/Licenses.html
> Add license

- Client/Ecosia/UI/EcosiaHome.swift
- Client/Frontend/Browser/TabTrayControllerV1.swift
- Client/Frontend/Library/HistoryPanel.swift
> More analytics

- Client/Ecosia/UI/MarketsController.swift
> Make markets controller a themed table view controller

- .circleci/config.yml
- Client.xcodeproj/project.pbxproj
- Client/Configuration/Ecosia.xcconfig
- Client/Configuration/EcosiaBeta.xcconfig
- Client/Configuration/EcosiaDebug.xcconfig
- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/Migration/EcosiaFavourites.swift
- Client/Ecosia/Migration/EcosiaHistory.swift
- Client/Ecosia/Migration/EcosiaImport+PerformanceTests.swift
- Client/Ecosia/Migration/EcosiaImport.swift
- Client/Ecosia/Migration/EcosiaTabs.swift
- Client/Entitlements/EcosiaBeta.entitlements
- ClientTests/TestHistoryMigration.swift
- Extensions/Entitlements/EcosiaBeta.entitlements
- fastlane/Fastfile
- fastlane/Matchfile
- track migration errors and performance
- track browser errors
- deploy to beta and live testflight in parallel
> Migration tracking + appstore setup

- Client/Ecosia/UI/FilterController.swift
- Client/Frontend/Library/HistoryPanel.swift
Remove divider when there is no data
> Don't display empty cells

- .circleci/config.yml
- Client.xcodeproj/project.pbxproj
- fastlane/Fastfile
Have extra config `EcosiaAppCenter` for AppCenter adhoc builds. Old used config `EcosiaBeta` is now used for Testflight builds of the FF Beta
> Fix appcenter

- Client/Frontend/Widgets/PhotonActionSheet/AppMenu.swift
> create all entry points to library in app menu

- Client/Frontend/Library/DownloadsPanel.swift
> Increase download text width

- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
> move pin next to image

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
Use SPStructured Event instead of Timing event as this can be easier visualized in Looker
> Use structured Event for migration performance

- Client/Frontend/Library/HistoryPanel.swift
> remove border in Library cells

- Client/Frontend/Home/FirefoxHomeViewController.swift
> Make new tap page always bounce vertical

- Client/Frontend/Library/ReaderPanel.swift
> Adjustments: icons

- Client/Configuration/Ecosia.xcconfig
> change display name for prod version

- Client/Frontend/Library/BookmarksPanel.swift
- Client/Frontend/Theme/ThemedWidgets.swift
> Add accessory view

- Client/Ecosia/Migration/EcosiaFavourites.swift
> Make sure database is open before migration

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Browser/OpenSearch.swift
- Client/Frontend/Browser/Tab.swift
- ClientTests/SearchTests.swift
> enable x-platform analytics

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/Tab.swift
> Update ecosified API

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/Migration/AppDelegate+Ecosia.swift
> Add migration success event

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/Migration/AppDelegate+Ecosia.swift
- Client/Ecosia/Migration/EcosiaFavourites.swift
- Client/Ecosia/Migration/EcosiaHistory.swift
- Client/Ecosia/Migration/EcosiaImport+PerformanceTests.swift
- Client/Ecosia/Migration/EcosiaImport.swift
- Client/Frontend/Library/BookmarkDetailPanel.swift
- Client/Frontend/Library/BookmarksPanel.swift
- Client/Frontend/Settings/AppSettingsOptions.swift
- Client/Frontend/Settings/AppSettingsTableViewController.swift
- Client/Utils/FaviconFetcher.swift
- ClientTests/TestHistoryMigration.swift
- create migration test scenario for favs and history via debug menu
- propagate success to outer world
- only show mobile bookmarks
> Mob 945 add migration scenario

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/xcshareddata/xcschemes/Ecosia.xcscheme
- Client/Ecosia/Migration/EcosiaFavourites.swift
- Client/Frontend/Browser/TabManagerStore.swift
- ClientTests/EcosiaBookmarkTests.swift
- ClientTests/TabManagerMigrationTests.swift
Made a test but had to comment it as I noticed it is flaky and sometimes the `RustPlaces` can't load the bookmarks; I opted to leave the code commented instead of delete as it can be improved as I learn more about RustPlaces.
> Migration error bookmarks

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Fixes infinite opening of Apple Maps tabs
- Still pending in FF repo: https://github.com/mozilla-mobile/firefox-ios/issues/7363 -> will check to push it upstream
> Fix infinite apple maps tabs

- Client/Frontend/Browser/URLBarView.swift
> Do not show reload/cancel on Home

- Client.xcodeproj/project.pbxproj
- Client/Application/LaunchScreen.xib
- Client/Info.plist
> Fix splash screen for iOS13 and below

- README.md
@vauxhall  We both worked today on L10N with transifex - could be I overwrote yours 🙈 I adjust the workflow to also pull the source file before pushing it
> Update Readme.md for L10N Updates

- Client/Application/AppDelegate.swift
- Client/Application/NavigationRouter.swift
- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/EcosiaSettings.swift
- Client/Ecosia/UI/EcosiaHome.swift
- Client/Ecosia/UI/MarketsController.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Browser/TabManager.swift
- Client/Frontend/Browser/TabTrayControllerV1.swift
- Client/Frontend/Browser/TopTabsViewController.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
- Client/Frontend/Library/BookmarksPanel.swift
- Client/Frontend/Library/HistoryPanel.swift
- Client/Frontend/Share/ShareExtensionHelper.swift
- Client/Frontend/Widgets/PhotonActionSheet/AppMenu.swift
- Client/Frontend/Widgets/PhotonActionSheet/PageActionMenu.swift
Added, removed and refactored events according to tracking sheet
> Streamline tracking

- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
Is not only for iPad, but also for Landscape on iPhone
> Big screens alignment

- Client/Frontend/Browser/BrowserViewController.swift
> Hide welcome screen if it is first time

- Client/Frontend/Home/FirefoxHomeViewController.swift
> center top sites in landscape

- Client/Frontend/Browser/BrowserViewController.swift
> Stop animating tab icon when launching

- Client/Frontend/Browser/BrowserViewController.swift
cherry picked from https://github.com/mozilla-mobile/firefox-ios/pull/7438/files
> Photo library crash - Simpler Photo handling (#7438)

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/Migration/EcosiaHistory.swift
- ClientTests/TestHistoryMigration.swift
> Retry failed with history migration with less data

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/UI/EcosiaHome.swift
- Client/Ecosia/UI/NewsCell.swift
- Client/Ecosia/UI/NewsController.swift
- persistence added for news
- only loaded once per day
- loaded next day on appear of screen if app is not getting killed
> Mob 989 news loading

- Client.xcodeproj/project.pbxproj
- Client/Application/NavigationRouter.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/SavedTab+ConfigureExtension.swift
- Client/Frontend/Browser/SavedTab.swift
- Client/Frontend/Browser/SiteArchiver.swift
- Client/Frontend/Browser/Tab.swift
- Client/Frontend/Browser/TabManager.swift
- Client/Frontend/Browser/TabManagerStore.swift
- Shared/Prefs.swift
- WidgetKit/OpenTabs/OpenTabsWidget.swift
- WidgetKit/OpenTabs/SimpleTab.swift
- WidgetKit/OpenTabs/TabProvider.swift
> Fix widget crash

- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
> Fix fonts on NTP

- Client/Ecosia/UI/EcosiaHome.swift
> Move done button to the right

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/UI/EcosiaHome.swift
- use latest core
- use new publisher API to load news
> Use new publisher API in news

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Browser/Tab.swift
- Client/Frontend/Browser/TabManager.swift
Had to open again due to misspelled uppercase branch name
same like https://github.com/ecosia/ios-browser/pull/97
> Use static Cookie API

- Client/Frontend/Home/FirefoxHomeViewController.swift
> Hide promo for searchbar focus

- Shared/UserAgent.swift
> Update default user agent

- Client/Ecosia/UI/EcosiaHome.swift
- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Ecosia/UI/NewsCell.swift
- Client/Ecosia/UI/NewsController.swift
> Adjust Layout for News Cells

- Client/Ecosia/UI/EcosiaHome.swift
> Add nav bar scroll separators in Ecosia World

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
> Tracking in top sites

- Client/Ecosia/UI/EcosiaHome.swift
- Client/Ecosia/UI/EcosiaNavigation.swift
- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Ecosia/UI/NewsController.swift
- Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheet.swift
- Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetCell.swift
> Lighter Background for Ecosia Home dark mode

- Client/Application/AppDelegate.swift
- Client/Ecosia/UI/EcosiaNavigation.swift
> Fix status bar appearance for Ecosia World

- Client/Info.plist
- Client/en.lproj/InfoPlist.strings
> Fix camera usage description

- Client/Ecosia/UI/EcosiaHome.swift
- Client/Frontend/Home/DefaultBrowserCard.swift
> Tweak top nav for news

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
> gmsg:// hot fix

- Extensions/ShareTo/ShareViewController.swift
> Fix crash in share extension

- Client.xcodeproj/xcshareddata/xcschemes/Ecosia.xcscheme
- Client/Ecosia/UI/EcosiaExploreCell.swift
- Client/Ecosia/UI/EcosiaInfoCell.swift
- Client/Ecosia/UI/NewsCell.swift
- Client/Ecosia/UI/NewsController.swift
- Client/Ecosia/UI/TreeCounterCell.swift
- Client/Frontend/Home/DefaultBrowserCard.swift
- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
> tweak ntp and news layout

- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Frontend/Browser/TabTrayButtonExtensions.swift
- Client/Frontend/Widgets/ToggleButton.swift
> Fix button colours

- Client.xcodeproj/project.pbxproj
Localized strings not added to the project file.
> Fix shortcut items title

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> Don't focus on search field

- Client/Frontend/Browser/BrowserViewController.swift
Fixes showing reader icon on NTP is some edge case. See https://ecosia.d.pr/P43MGp
> dont show reader icon on NTP / Home

- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
> use fixed corner radius for top site cells

- Client/Application/AppDelegate.swift
- Client/Ecosia/UI/MarketsController.swift
Temporary deactivate Feature Flagging as we don't use it at the moment
> comment entry points to goodall

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/UI/MyImpact/EcosiaExploreCell.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/MyImpact/EcosiaHomeCells.swift
- Client/Ecosia/UI/MyImpact/EcosiaHomeLayout.swift
- Client/Ecosia/UI/MyImpact/MultiplyImpactCell.swift
- Client/Ecosia/UI/MyImpact/MyImpactCell.swift
- Client/Ecosia/UI/MyImpact/NewsCell.swift
Fixing Home and Ecosia World layout for iPad and iPhone Landscape
> Jeh fix home ipad layout

- Shared/UserAgent.swift
Bringing back the Safari bit (like also Firefox and Chrome have it)
> Add Safari bit to user agent

- Client/Ecosia/UI/MyImpact/EcosiaExploreCell.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Frontend/Home/FirefoxHomeTopSitesCell.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
Bringing the changes from https://github.com/ecosia/ios-browser/pull/158 to main with some adaptations
> layout fixes for ipad in split views

- Client/Frontend/Browser/URLBarView.swift
Hide new tab button on iPad (it was duplicated)
> Hide new tab button on iPad

- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Settings/AppSettingsOptions.swift
- Client/Frontend/Settings/AppSettingsTableViewController.swift
- Shared/Prefs.swift
https://ecosia.atlassian.net/browse/MOB-1249
> MOB-1249 remove autofocus, limit NTP animation

- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
Adjusting cell height if dynamic type is bigger.
> Fix separator

- WidgetKit/ImageButtonWithLabel.swift
https://ecosia.atlassian.net/browse/MOB-1280
> Fix quicklink widget color

- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
Now will all the change set - forgot it in my last PR 🙈
> Fix tab navigation bar colors for iPad Pt. 2

- Client/Frontend/Widgets/PhotonActionSheet/PageActionMenu.swift
https://ecosia.atlassian.net/browse/MOB-1327
> Only open in Safari for http and https url

- Client/Frontend/Library/HistoryPanel.swift
https://ecosia.atlassian.net/browse/MOB-1326
> History: reload when last item is deleted

- Client/Ecosia/L10N/String.swift
- Client/Ecosia/L10N/de.lproj/Plurals.stringsdict
- Client/Ecosia/L10N/en.lproj/Plurals.stringsdict
- Client/Ecosia/L10N/es.lproj/Plurals.stringsdict
- Client/Ecosia/L10N/fr.lproj/Plurals.stringsdict
- Client/Ecosia/L10N/it.lproj/Plurals.stringsdict
- Client/Ecosia/L10N/nl.lproj/Plurals.stringsdict
- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Ecosia/UI/MyImpact/MultiplyImpact.swift
- Client/Ecosia/UI/MyImpact/NewsCell.swift
https://ecosia.atlassian.net/browse/MOB-1363
> Referrals design qa

- Client/Ecosia/Analytics/Analytics.swift
FYI:
Fixed an issue with referrals promo tracking, and I will keep this branch in case we need to add more fixes or create a new release candidate without the rebranding elements.
> Fix show invite promo issue (probably caused by merge conflicts)

- Client/Frontend/Login Management/LoginListViewController.swift
Further customization of the search controller search bar will be left for a later stage.
> Rebranding settings login search

- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+URLBarDelegate.swift
- Client/Frontend/Browser/ButtonToast.swift
- Client/Frontend/Browser/SimpleToast.swift
- Client/Frontend/Browser/TabPeekViewController.swift
- Client/Frontend/Browser/Tabs/TabMoreMenuViewController.swift
- Client/Frontend/Library/BookmarksPanel.swift
- Client/Frontend/Library/HistoryPanel.swift
- Client/Frontend/Settings/SearchSettingsTableViewController.swift
- Client/Frontend/Widgets/PhotonActionSheet/PhotonActionSheetProtocol.swift
All toasts come with images now 🥪
> Fix all the toasts

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/UI/NTP/TreesCell.swift
> don't animate global count for reduced motion

- Client/Ecosia/UI/MyImpact/EcosiaNavigation.swift
Design QA for https://ecosia.atlassian.net/browse/MOB-1454 fixing the iPad layout issues
> Present your Impact and Referrals in a popover on iPad

- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/NTP/TreesCell.swift
- Client/Ecosia/UI/NTP/TreesCellModel.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
fixes https://ecosia.atlassian.net/browse/MOB-1489
> Fix impact cell dark mode layout when referrals is off

- Client/Application/AppDelegate.swift
- Client/Ecosia/UI/MyImpact/EcosiaNavigation.swift
- Client/Ecosia/UI/NTP/DefaultBrowser.swift
- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
- Client/Frontend/Library/LibraryViewController/LibraryViewController.swift
fixes https://ecosia.atlassian.net/browse/MOB-1491
> unify status bar appearance for modals

- Client/Frontend/Browser/Tabs/EmptyPrivateTabsView.swift
- Client/Frontend/Library/ReaderPanel.swift
fixes issues from https://ecosia.atlassian.net/browse/MOB-1323
> Fix reader texts and design

- Client/Ecosia/UI/NTP/TreesCell.swift
- Client/Ecosia/UI/Onboarding/WelcomeTourAction.swift
fixes https://ecosia.atlassian.net/browse/MOB-1506
> use global tree count in onboarding

- Client/Frontend/Browser/Tab.swift
- Client/Frontend/Browser/TabManager.swift
- Client/Frontend/Browser/URLBarView.swift
fixes https://ecosia.atlassian.net/browse/MOB-1469
> update keyboard appearance with theme

- Client/Frontend/Theme/DarkTheme.swift
- Client/Frontend/Theme/Theme.swift
- Client/Frontend/Theme/ThemedWidgets.swift
fixes https://ecosia.atlassian.net/browse/MOB-1422
> Settings color tweaks

- Client/Frontend/Browser/GridTabViewController.swift
- Client/Frontend/Browser/Tabs/ChronologicalTabsViewController.swift
- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
- Client/Frontend/Browser/Tabs/TabTrayViewModel.swift
fixes https://ecosia.atlassian.net/browse/MOB-1525
> Fix close tabs crash ipad

- Client/Frontend/Browser/GridTabViewController.swift
https://ecosia.atlassian.net/browse/MOB-1465
> fix tab cell corner radius

- Client/Frontend/Browser/TabTrayButtonExtensions.swift
- Client/Frontend/Browser/TopTabsViewController.swift
- Client/Frontend/Widgets/ToggleButton.swift
https://ecosia.atlassian.net/browse/MOB-1463
> fix and unify private button layout

- Client/Ecosia/UI/NTP/NTPLayout.swift
- Client/Ecosia/UI/NTP/NTPTooltip.swift
- Client/Ecosia/UI/NTP/TreesCell.swift
https://ecosia.atlassian.net/browse/MOB-1499
> Move ntp tooltip closer to cell

- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+URLBarDelegate.swift
Finally found the icons with the problem
> Fixed snackbar for bookmarks

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
- Client/Frontend/Widgets/PhotonActionSheet/AppMenu.swift
> Tracking block images

- PULL_REQUEST_TEMPLATE
I took inspiration from what they do in core
> change PR template [skip ci]

- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/UI/MyImpact/MultiplyImpact.swift
https://ecosia.atlassian.net/browse/MOB-1581
> Add tracking event for invitations learn more

- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/MyImpact/MyImpactCell.Indicator.swift
- Client/Ecosia/UI/MyImpact/MyImpactCell.Progress.swift
- Client/Ecosia/UI/MyImpact/MyImpactCell.swift
[MOB-####](https://ecosia.atlassian.net/browse/MOB-####)
> Fix tappable progress bar

- Client/Application/AppDelegate.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+URLBarDelegate.swift
- Client/Frontend/Browser/Tabs/ChronologicalTabsViewController.swift
- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
- Client/Frontend/Library/LibraryViewController/LibraryViewController.swift
- Client/Frontend/Settings/ThemeSettingsController.swift
- Client/Frontend/Theme/ThemeManager.swift
Cherry-picking FF solution to apply manual theme for webview 🍒 
[MOB-1583](https://ecosia.atlassian.net/browse/MOB-1583)
> Set the `overrideUserInterfaceStyle` on the window and not per view (#8568)

- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
[MOB-1542](https://ecosia.atlassian.net/browse/MOB-1542)
Solved by removing multiple reloads of ImpactCell
> Updating UI directly instead or reload to avoid flash

- Client/Frontend/Library/ReaderPanel.swift
[MOB-####](https://ecosia.atlassian.net/browse/MOB-####)
> Align icons on Reading List Panel empty state.

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/xcshareddata/xcschemes/Ecosia.xcscheme
- Client/Ecosia/Extensions/HomepageViewController+Ecosia.swift
- Client/Ecosia/UI/NTP/NTPImpactViewModel.swift
- Client/Ecosia/UI/NTP/NTPTooltip.Highlight.swift
- Client/Frontend/Toolbar+URLBar/LockButton.swift
- Client/Frontend/Toolbar+URLBar/URLBarView.swift
- Tests/ClientTests/Ecosia/EcosiaBookmarkMigrationTests.swift
- Tests/ClientTests/Ecosia/EcosiaHistoryMigrationTests.swift
- Tests/ClientTests/Ecosia/EcosiaNTPTooltipHighlightTests.swift
- Tests/ClientTests/Ecosia/EcosiaTabMigrationTests.swift
- Tests/ClientTests/TabManagerStoreTests.swift
- bring back Ecosia migration Unit tests
- finalise search bar UI
- add tests for NTP tooltip
> More searchbar fixes

- Client/Ecosia/UI/EmptyHeader.swift
- Client/Frontend/Library/Bookmarks/BookmarksPanel.swift
- Client/Frontend/Library/DownloadsPanel.swift
- Client/Frontend/Library/HistoryPanel/HistoryPanel.swift
- Client/Frontend/Library/LibraryViewController/LibraryViewController.swift
- Client/Frontend/Library/ReaderPanel.swift
- Client/Frontend/Theme/LegacyThemeManager/LegacyDarkTheme.swift
- Client/Frontend/Theme/LegacyThemeManager/LegacyTheme.swift
- Client/Frontend/Toolbar+URLBar/TabLocationView.swift
[MOB-1600](https://ecosia.atlassian.net/browse/MOB-1600)
> history search design qa

- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Frontend/Browser/GridTabViewController.swift
- Client/Frontend/Browser/TabDisplayManager.swift
- Client/Frontend/Browser/Tabs/InactiveTabCell.swift
- Client/Frontend/Browser/Tabs/InactiveTabHeader.swift
- Client/Frontend/Browser/Tabs/InactiveTabItemCell.swift
- Client/Frontend/Browser/Tabs/InactiveTabViewModel.swift
- Client/Frontend/Contextual Hint/ContextualHintViewController.swift
- Client/Frontend/Contextual Hint/ContextualHintViewModel.swift
- Client/Frontend/Settings/AppSettingsOptions.swift
- Client/Frontend/Settings/AppSettingsTableViewController.swift
- Client/Frontend/Settings/TabsSettingsViewControler.swift
[MOB-1597](https://ecosia.atlassian.net/browse/MOB-1597)
> inactive tabs

- Client/Ecosia/UI/NTP/Cells/NTPImpactCell.swift
- Client/Frontend/Browser/TopTabsLayout.swift
- Client/Frontend/Browser/TopTabsViewController.swift
- Client/Frontend/Browser/TopTabsViews.swift
- Client/Frontend/Home/HomepageSectionType.swift
- Client/Frontend/Home/TopSites/TopSitesDimension.swift
- Tests/ClientTests/Frontend/Home/TopSites/TopSitesDimensionTests.swift
> Ipad cosmetics

- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
> fix missing image in toast

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/UI/PageAction/PageActionsShortcutsHeader.swift
- Client/Frontend/Browser/MainMenuActionHelper.swift
[MOB-1653](https://ecosia.atlassian.net/browse/MOB-1653)
[MOB-1654](https://ecosia.atlassian.net/browse/MOB-1654)
> Analytics for new menu usage 

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
- Client/Frontend/Browser/MainMenuActionHelper.swift
- Client/Frontend/Widgets/OneLineCellAndFooter.swift
> Fix more images for the toasts

- Client/Ecosia/Extensions/HomepageViewController+Ecosia.swift
- Client/Ecosia/UI/MarketsController.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.Section.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/NTP/NTPImpactViewModel.swift
- Client/Frontend/Settings/AppSettingsOptions.swift
- Client/Frontend/Settings/AppSettingsTableViewController.swift
🌆 🦍 
https://ecosia.atlassian.net/browse/MOB-1656
> sunset goodall

- Client/Frontend/Login Management/AddCredentialViewController.swift
- Client/Frontend/Login Management/LoginDetailTableViewCell.swift
- Client/Frontend/Login Management/LoginListViewController.swift
- Client/Frontend/Settings/LoginDetailViewController.swift
- Client/Frontend/Theme/LegacyThemeManager/ThemedTableSectionHeaderFooterView.swift
> fix layout bugs in password settings

- Client/Ecosia/UI/Onboarding/Welcome.swift
https://ecosia.atlassian.net/browse/MOB-1657
Fix 🌑 🌞 for onboarding
> Fix initial theme for onboarding

- Client.xcodeproj/project.pbxproj
- Client/Ecosia/Extensions/HomepageViewController+Ecosia.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.Section.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/MyImpact/EcosiaHomeCells.swift
- Client/Ecosia/UI/MyImpact/NewsCell.swift
- Client/Ecosia/UI/NTP/NTPNewsViewModel.swift
- Client/Frontend/Components/LabelButtonHeaderView.swift
- Client/Frontend/Home/HomepageSectionType.swift
- Client/Frontend/Home/HomepageViewController.swift
- Client/Frontend/Home/HomepageViewModel.swift
[MOB-1612](https://ecosia.atlassian.net/browse/MOB-1612)
- moving 📰  to 🏠
> News on ntp

- Client.xcodeproj/project.pbxproj
- Client/Nimbus/NimbusFeatureFlagLayer.swift
[MOB-1651](https://ecosia.atlassian.net/browse/MOB-1651)
> Never start on home, always last tab

- Client/Ecosia/UI/PageAction/PageActionMenu.swift
[MOB-1661](https://ecosia.atlassian.net/browse/MOB-1661)
- add swipe down gesture to close menu in iPhone Landscape 📱 🖼️
> add swipe down to close menu in phone landscape

- Client/Frontend/Browser/ClipboardBarDisplayHandler.swift
- Client/Frontend/Browser/TabManager.swift
> Fix two more toast images [skip ci]

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/MetadataParserHelper.swift
- Client/Frontend/TabContentsScripts/UserScriptManager.swift
[MOB-1677](https://ecosia.atlassian.net/browse/MOB-1677)
- injects and reads local storage value for the cookie consent
- use updated core from this PR https://github.com/ecosia/ios-core/pull/68
> Cookie consent

- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
- Client/Frontend/Home/HomepageViewModel.swift
2 small after release bugfixes 🐛 
- readd missing referrals promo impression event
- fix title in tabs not updating after toggling private mode
> Bugfixes 8.0.0

- Client/Ecosia/Migration/EcosiaFavourites.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Home/HomepageContextMenuHelper.swift
- Client/Frontend/Library/Bookmarks/BookmarkDetailPanel.swift
- Client/Frontend/Library/Bookmarks/BookmarksPanelViewModel.swift
- Extensions/ShareTo/ShareViewController.swift
- Storage/Rust/RustPlaces.swift
- Tests/ClientTests/RatingPromptManagerTests.swift
🍒 picking the fix for the bookmarks order bug 🐛 
- fixes [MOB-1681](https://ecosia.atlassian.net/browse/MOB-1681)
- changed behaviour to add bookmarks at the end of the list like it was in older versions
> Bugfix FXIOS-4842 [v106] Mobile bookmark order (#11895)

- Client/Ecosia/Analytics/Analytics.swift
[MOB-1684](https://ecosia.atlassian.net/browse/MOB-1684)
- as discussed with BI this optimises and surfaces which automatic events and contexts we send
> explicit SnowPlow Config

- Client/Ecosia/Analytics/Analytics.swift
- Client/Frontend/Browser/MainMenuActionHelper.swift
[MOB-####](https://ecosia.atlassian.net/browse/MOB-####)
> Add invitations event

- Client.xcodeproj/project.pbxproj
- Client/Ecosia/UI/NTP/News/NTPNewsViewModel.swift
- Tests/ClientTests/Ecosia/EcosiaNTPNewsViewModelTests.swift
[MOB-1683](https://ecosia.atlassian.net/browse/MOB-1683)
- Filter out tree store news while tree store promo is active
> filter out tree store duplicate

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
- Client/Frontend/Browser/GridTabViewController.swift
- Client/Frontend/Browser/TabManager.swift
- Client/Frontend/Browser/TopTabsViewController.swift
- remove obsolete events
- added missing events after upgrade
- some general clean up
> clean analytics

- Client/Frontend/Browser/MainMenuActionHelper.swift
- Client/Frontend/Toolbar+URLBar/TabLocationView.swift
[MOB-1692](https://ecosia.atlassian.net/browse/MOB-1692)
- cherry picks fix from FF to address sharing of downloaded files 🍒 
- fix layout issue when displaying file urls
> Fix to share pdf

- Client/Frontend/Browser/TopTabsViewController.swift
[MOB-1699](https://ecosia.atlassian.net/browse/MOB-1699)
> Increase width for iPad tab cards

- Client/Application/AppDelegate.swift
Somehow these two events did not make it though the upgrade ☹️
> Fix missing lifecycle analytics

- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/UI/Impact/MultiplyImpact.swift
[MOB-1611](https://ecosia.atlassian.net/browse/MOB-1611)
> Mob 1611 link copying qa

- .gitignore
- .tx/config
- README.md
@TimNowaczynski @jman82 @rashmi-ecosia 
This is mostly FYI
Might be needed for your local transifex clients as well. Depending on when you installed transifex.
Major changes:
- new format of .tx/config
- add api token to your local ~/.transifexrc
> use transifex API v3

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Analytics/Analytics.swift
- Client/Ecosia/Extensions/BrowserViewController+Ecosia.swift
- Client/Ecosia/UI/PageAction/PageActionsShortcutsHeader.swift
- Client/Frontend/Browser/MainMenuActionHelper.swift
[MOB-1701](https://ecosia.atlassian.net/browse/MOB-1701)
[MOB-1710](https://ecosia.atlassian.net/browse/MOB-1710)
tweak some analytics
> MOB-1701-1710 Add analytics for menu status and sharing property

- Client/Frontend/Browser/SearchViewController.swift
[MOB-1715](https://ecosia.atlassian.net/browse/MOB-1715)
- fix array out of bounds by using safe indeces
> MOB-1715 fix crash in autocomplete

- Client/Frontend/Browser/Tab.swift
[MOB-1718](https://ecosia.atlassian.net/browse/MOB-1718)
> MOB-1718 do not add sp param for incognito

- Shared/UserAgent.swift
[MOB-1717](https://ecosia.atlassian.net/browse/MOB-1717)
- fixes that Cloudflare, Facebook, Instagram and potentially some more websites don't like our user agent 🚀
> MOB-1717 add version bit to user agents

- Client/Frontend/Browser/TabManager.swift
[MOB-1721](https://ecosia.atlassian.net/browse/MOB-1721)
> MOB-1721 inject cookie on config init

- Client/Ecosia/Extensions/HomepageViewController+Ecosia.swift
- Client/Ecosia/Extensions/Unleash.DefaultBrowser.swift
- Client/Ecosia/UI/NTP/NTPImpactViewModel.swift
- Client/Ecosia/UI/NTP/NTPTooltip.Highlight.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/GridTabViewController.swift
- Client/Frontend/Home/HomepageViewModel.swift
- Tests/ClientTests/Ecosia/EcosiaNTPTooltipHighlightTests.swift
Fixes for [MOB-1705](https://ecosia.atlassian.net/browse/MOB-1705)
> Mob 1705 fixes

- Client/Application/NavigationRouter.swift
- Client/Ecosia/Analytics/Analytics.swift
[MOB-1706](https://ecosia.atlassian.net/browse/MOB-1706)
> Mob 1706 experiment analytics

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Home/HomepageViewController.swift
[MOB-1705](https://ecosia.atlassian.net/browse/MOB-1705)
- increase delay
- use updated core with more robust tree count
> Mob 1705 fixes next iteration

- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
- Client/Frontend/Browser/Tabs/TabTrayViewModel.swift
[MOB-1749](https://ecosia.atlassian.net/browse/MOB-1749)
> MOB-1749 iPad remove synced tabs

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- package-lock.json
This PR provides the updates for the upcoming Xcode 14.3.
Changes includes:
- solving the issue of `WebKit` not correctly loading the `WKWebView` on the simulator only.
- updating `Kingfisher` to work with the newer Xcode version.
- updates on `npm` dependencies
> Updates for new xcode 14 3

- .circleci/config.yml
[MOB-1819](https://ecosia.atlassian.net/browse/MOB-1819)
We have implemented the Dynamic Configuration on CircleCI.
We started to face Max number of workflows exceeded in the CirleCI dashboard.
A handy [troubleshooting guide](https://support.circleci.com/hc/en-us/articles/360060934851-Troubleshooting-Error-Message-Max-number-of-workflows-exceeded-) has been found.
This PR addresses the implementation and reviews workflows and jobs namings.
> MOB-1819 Max workflows exceeded CircleCI fix

- Client/Ecosia/UI/Onboarding/WelcomeTourGreen.swift
- Client/Ecosia/UI/Onboarding/WelcomeTourProfit.swift
[MOB-1846]
As part of Onboarding design QA, an inconsistency with font sizes was [reported](https://ecosia.atlassian.net/browse/MOB-1846?focusedCommentId=83090).
Adjust the expected font sizes and styles.
[MOB-1846]: https://ecosia.atlassian.net/browse/MOB-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-1846] Adjust onboarding font sizes

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Application/AppDelegate.swift
- Client/Ecosia/Extensions/DeviceInfo+Ecosia.swift
- Client/Ecosia/MMP/MMP.swift
- Client/Ecosia/UI/Onboarding/Welcome.swift
- Client/Ecosia/UI/Onboarding/WelcomeTour.swift
[MOB-2407]
Adding post-session MMP events so we can measure campaign-based activation.
Uses the new method from https://github.com/ecosia/ios-core/pull/140 and handles each event described on the ticket.
- Also fixes [this countryCode bug](https://ecosia.atlassian.net/browse/MOB-2502)
[MOB-2407]: https://ecosia.atlassian.net/browse/MOB-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
___
enhancement, bug_fix
___
- Enhanced MMP integration by adding event handling for search counts and onboarding events.
- Simplified country code retrieval across all iOS versions.
- Updated dependencies in Xcode project files, including a significant update to SDWebImage.
___
<table><thead><tr><th></th><th align="left">Relevant …
> [MOB-2407] Post-session MMP events

- firefox-ios/Ecosia/Ecosia.docc/Ecosia.md
[MOB-####]
Ecosia Readme for bootstrapping / Getting started is outdated.
> Fix discrepancies in Ecosia Readme
