ecosia/ios-browser

- fastlane/Fastfile
Fastlane docs state that 2FA authentication can be skipped by providing those arguments to `pilot` .
http://docs.fastlane.tools/actions/pilot/#use-an-application-specific-password-to-upload
I also create a fresh specific application password. Let's see if that works out at next release
> try to skip 2FA for testflight

- Client/Frontend/Browser/Tab.swift
notice: `completion?(webView.load(request))` won't call webView.load(request) if `completion` is nil - how could I miss this 🙈
> MOB-895 fix missed load due to nil completion

- Client/Frontend/Browser/URLBarView.swift
Avoid showing stop button on search bar when progress is 0 (after clicking back for example)
> Don't show stop when progress is zero

- Client/Ecosia/Migration/AppDelegate+Ecosia.swift
For the moment only called after migration success, maybe to implement retries.
> Add cleanup method

- Client/Ecosia/Migration/EcosiaHistory.swift
- Client/Ecosia/Migration/EcosiaImport.swift
An option is to check whether the connection to the DB is still open after prepare but before inserting the new data.
This at least prevents leaving the app in an undefined state.
> Migration error: db connection not open

- Client/Ecosia/Migration/AppDelegate+Ecosia.swift
- Client/Ecosia/Migration/EcosiaImport+PerformanceTests.swift
- ClientTests/TestHistoryMigration.swift
- Providers/Profile.swift
- make migration more resilient
- increase migration test scenario to 1000 days of history (was 100)
- do not close profile when migration has not finished (so continues after going to BG)
- tested on iPhone 7
> Don't close DB when migration is still ongoing / tweak scenario

- Client/Ecosia/Migration/EcosiaHistory.swift
- ClientTests/TestHistoryMigration.swift
- Storage/SQL/SQLiteHistory.swift
Improve migration preparation speed for history by using internal Foundation-Dictionary lookup instead of regular string comparision
> use dict to speed up existing urls lookup

- ecosify-strings.py
3 more cases are now covered:
- Firefox in different languages is replaced
- string comparison is case-insensitive now
- orphaned lines in .string-files are considered like `Firefox";`
> improve l10n replacement script

- Client/Ecosia/EcosiaSettings.swift
- Client/Frontend/Settings/AppSettingsOptions.swift
- Client/Frontend/Theme/ThemedWidgets.swift
Cell autosizing for UITableViewCell Style **Value1** is broken when textLabel is very long and would need multiple lines even in latest iOS14 starting from iOS11. This fixes it with some very ugly pixel calculation code ^^
> Fix autosizing of .value1 table view cells in settings

- Client/Ecosia/Analytics/Analytics.Values.swift
- Client/Ecosia/Migration/EcosiaImport.swift
- Client/Ecosia/Migration/LoadingScreen.swift
- detect and persist exception during migration
- if exception occured -> send reason to Analytics and skip migration
> Skip migration after it had crashed

- Client/Application/AppDelegate.swift
- Client/Ecosia/Migration/LoadingScreen.swift
- ClientTests/MockProfile.swift
- Providers/Profile.swift
- aims at fixing https://ecosia.atlassian.net/browse/MOB-1013 
- encapsulates migration in BackGround Task
- closes profile after migration is done in background
> Continue migration in background task

- Client/Frontend/Browser/BrowserViewController.swift
- Shared/AppConstants.swift
After some testing and being unable to reproduce the crashes, my understanding is that it could be related to KVO behaving as case sensitive in some cases regarding `URL`. (It is actually `url` the property in `WKWebView`).
> Fix browser crash

- Client/Frontend/Browser/BrowserViewController.swift
Turns out the backdrop is only needed when the app is resigning active. So it should be hidden when opening a new tab.
> Hide backdrop when opening a new tab

- Client/Ecosia/UI/EcosiaTheme.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/NTP/TreesCell.swift
- Client/Ecosia/UI/NTP/TreesCellModel.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
The same cell has a different appearance on ntp and my impact. Now fixed
> Fix TreesCell dark appearance for impact screen

- Client/Ecosia/Migration/LoadingScreen.swift
- Client/Ecosia/UI/MyImpact/EcosiaHome.swift
- Client/Ecosia/UI/MyImpact/EcosiaNavigation.swift
- Client/Ecosia/UI/MyImpact/MultiplyImpact.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Home/FirefoxHomeViewController.swift
- ClientTests/FirefoxHomeTests.swift
- Fix mismatch between referral counts
- use dependency injection to provide referrals instance across different view controllers
- original referrals instance lives in BrowserViewController
> Sync referral instances

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
https://ecosia.atlassian.net/browse/MOB-1378
I always had the impression that screenshots in the tabswitcher were not correctly updated. Finally I could reproduce and fix it 🤞
> Use method through BVC to open new tab (fixes missing screenshot)

- Client/Ecosia/UI/NTP/DefaultBrowser.swift
- Client/Frontend/Browser/BrowserViewController.swift
- present default browser as sheet on iPad
- enable native swipe down by standard iOS modal presentation for phones
> tweak default browser presentation for iPad

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
- Client/Frontend/Browser/TabManager.swift
- fixes https://ecosia.atlassian.net/browse/MOB-1516 
- now we also monitor async cookie changes that originate from the Frontend
> observe cookie store instead of manual fetch

- Client/Frontend/Browser/TabTrayButtonExtensions.swift
- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
When UIBarButtonItems have a custom view, iOS indents it according to safe area layout margin. So the solution to have the center item centered, was to make the right item (delete button) use a custom view as well 🤯
> Center add tab button

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Upgrade SnowPlow to Version 3.2.0 from 2.2.0
- followed the migration guide from [SnowPlow](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/migration-guides/migration-guide-for-snowplow-ios-tracker-sdk-from-version-2-x-to-3-0)
- fortunately there are no breaking changes and it just works 🎉 
- tested with SnowPlow Mini and events are arriving with updated Tracker version
> Upgrade snowplow SDK to current version 3.2.0

- Client/Frontend/Home/HomepageSectionType.swift
- Client/Frontend/Home/TopSites/TopSitesDimension.swift
- Tests/ClientTests/Frontend/Home/TopSites/TopSitesDimensionTests.swift
Using screen traits instead of device traits to determine NTP layout. That way it also works for SplitViews on iPad OS
> Fix split view for iPad

- Client/Ecosia/Extensions/HomepageViewController+Ecosia.swift
- Client/Ecosia/UI/NTP/Cells/NTPImpactCell.swift
- Client/Ecosia/UI/NTP/News/NewsController.swift
- Client/Frontend/Home/HomepageViewController.swift
[MOB-1682](https://ecosia.atlassian.net/browse/MOB-1682)
- potential fix for crashes inside of UICollectionViewCompositionalLayout
- we use this on NTP (HomePageViewController) and News (NewsController)
- the crash reports don't indicate where exactly it happens
- The potential fix makes sure that `invalidateLayout` is only called when also the data is updated accordingly (hint taken from Mozilla codebase)
> Mob 1682 fix reload ntp crash

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/Tab.swift
- Client/Frontend/Browser/TabManager.swift
[MOB-1705](https://ecosia.atlassian.net/browse/MOB-1705)
This optimises Cookie injection solving side effects of injecting them too often. Before they were injected with every request and reload. Now they are only injected on startup and on relevant search setting changes.
> MOB-1705 improve cookie injection

- Client.xcodeproj/project.pbxproj
- Client/Application/ImageIdentifiers.swift
- Client/Frontend/Toolbar+URLBar/URLBarView.swift
- Client/Info.plist
- Tests/ClientTests/Frontend/Home/URLBarViewTests.swift
[MOB-1643](https://ecosia.atlassian.net/browse/MOB-1643)
- Updating the icon reference from `quick_action_new_private_tab` to `privateSearch` throughout the codebase
- Added minimum test scenarios to make sure we always display the appropriate `URLBarView`'s search icon
> MOB-1643 icnognito icon update

- Client/Frontend/Library/ClearHistorySheetProvider.swift
- Client/Utils/HistoryDeletionUtility.swift
- Tests/ClientTests/HistoryDeletionUtilityTests.swift
[MOB-1750](https://ecosia.atlassian.net/browse/MOB-1750)
This PR fixes an issue in the history panel when a "Clear all" event happens.
The content has been cherry-picked from the master Firefox repo.
Reference https://github.com/mozilla-mobile/firefox-ios/pull/13744
> MOB-1750 Clear history doesn't clear recently visited

- Client/Ecosia/UI/PageAction/PageActionMenu.swift
- Client/Ecosia/UI/PageAction/PageActionMenuCell.swift
- Client/Ecosia/UI/PageAction/PageActionsShortcutsHeader.swift
[MOB-1633](https://ecosia.atlassian.net/browse/MOB-1633)
The QA process spotted some issues in the separator width when moving from portrait to landscape and vice versa.
I took the occasion not only to fix the separator constraints thinking of the approach for trailing and leading from the start; It's been an excellent opportunity to review the UX on landscape and improve the Table View original behavior, taking care of the safe area layouts too.
> MOB-1633 Sticky top menu separator improvements

- README.md
This PR adds a troubleshooting subsection to our building steps on the Readme.
Two errors I face while building the project for the first time were added to that section:
- Emulation support software not installed when running on Rosetta simulator
- Missing content-blocker-lib-ios files
> Readme build troubleshooting

- Client/Frontend/Home/TopSites/TopSitesDimension.swift
- Tests/ClientTests/Frontend/Home/TopSites/TopSitesDimensionTests.swift
[MOB-1644](https://ecosia.atlassian.net/browse/MOB-1644)
The approach to this bug has been quite conservative in the first place.
I considered keeping the six items per row while reviewing the vertical alignment when the items were less than 5.
However, after catching up with the design, the final decision went to keep the four items regardless of the hosting interface.
This way, the layout is consistent with the upper items in the New Tab Page (Bookmarks, History, Reading List, and Downloads).
Approached this ticket the standard way we usually update Firefox Codebase. Added the `//Ecosia` comment to explain the change.
Produced Loom video and got the design approval.
> MOB-1644 Top sites layout

- Client.xcodeproj/project.pbxproj
- Client/Ecosia/UI/Impact/Views/MyImpactCell+ViewFactories.swift
- Client/Ecosia/UI/Impact/Views/MyImpactCell.swift
- Client/Frontend/Home/TopSites/TopSitesDimension.swift
[MOB-1788](https://ecosia.atlassian.net/browse/MOB-1788)
## Context
The UI in the "Your Impact" section breaks when it comes to localized content in the "friends label" larger than its size.
After extensive testing and trying out different solutions without having to rewrite the inner view components, I realized that the UI design needed a different approach in its drawing. 
The Content View wasn't following the UICollectionView layout size directives.
I went after choosing the `UIStackView` as per the main container of the entire Search and Friends info.
The layout is the following:
- Cell Content View
- Progress View with buttons and icons
- Search and Friends container StackView
- Search Stack View with search view items
- Friends Stack View with friends view items 
A refactor to …
> MOB-1788 UI issue on Your Impact section

- Client/Frontend/Browser/GridTabViewController.swift
- Client/Frontend/Browser/Tabs/TabTrayViewController.swift
[MOB-1648](https://ecosia.atlassian.net/browse/MOB-1648)
Since close all tabs is a destructive action, we should change it's style accordingly.
For the action sheet, I continued using the system style and just switched it to destructive. I noticed the Figma text colours do not exactly match, but since that is the same case for the Cancel button, I assumed that is on purpose to use iOS default for such modals (will also raise this in the ticket as well).
Also updated the button in the bottom of the page using the ecosia theme colour, which matches exactly with Figma.
Use the comment pattern `// Ecosia:` so we can identify custom changes in FF code.
> Change close all tabs button to destructive style

- Client/Frontend/Toolbar+URLBar/TabToolbar.swift
[MOB-1645](https://ecosia.atlassian.net/browse/MOB-1645)
Remove small incognito badge on the bottom bar tabs item. This change is requested by Yann since it is firefox's approach of showing incognito and it is not "adding value to the interface, besides cluttering the bottom navigation with a non-legible icon. We have other visual cues on the app showing user browse incognito (eg. search bar)."
Just commented out the `privateModeBadge` ui component and all places where it was used with the Ecosia style comment explaining the change.
> Remove incognito icon from bottom bar

- Client/Frontend/Toolbar+URLBar/TabToolbar.swift
- Client/Frontend/Toolbar+URLBar/TabToolbarHelper.swift
- Client/Frontend/Toolbar+URLBar/URLBarView.swift
- Tests/ClientTests/TabToolbarHelperTests.swift
[MOB-1645](https://ecosia.atlassian.net/browse/MOB-1645)
Follow-up of [the previous PR](https://github.com/ecosia/ios-browser/pull/436) since during QA an error was found where the icon still appears on landscape 🙈
This issue happened since I missed that the tab button switched views on landscape (since then the bottom toolbar does not exist and the options are instead in the url bar view).
Therefore, I just removed the `privateModeBadge` from this other view as well. Since those two places are the only ones using the `TabToolbarProtocol`, I was also able to remove the `func privateModeBadge(visible: Bool)` from it.
> Fix remove incognito icon on landscape

- Client/Ecosia/UI/EcosiaFindInPageBar.swift
[MOB-1644](https://ecosia.atlassian.net/browse/MOB-1644)
Follow-up of [this PR](https://github.com/ecosia/ios-browser/pull/441) since Kunle reported a non-matching placeholder text colour.
> Update find in page search textfield placeholder colour

- .github/actions/prepare_environment/action.yml
- Shared/Accessibility.swift
[MOB-1814](https://ecosia.atlassian.net/browse/MOB-1814)
Builds started to fail because of missing content blocker scripts.
Investigation started. Looked at possible solutions.
Everything appeared to be in place, so I started questioning the (what should be) unquestionable.
It appears that the `if` statement within actions' steps are evaluated correctly only if passing `!= true` as provided in the [`cache`](https://github.com/actions/cache#skipping-steps-based-on-cache-hit) action examples.
I took the occasion to also improve the spm execution in case of missing cache for packages.
> MOB-1814 Fix ci content blocker cache

- Client/Application/AppDelegate.swift
- Client/Ecosia/FeatureManagement/FeatureManagement.swift
- Client/Ecosia/MMP/MMP.swift
- Client/Ecosia/Settings/EcosiaDebugSettings.swift
[MOB-1815](https://ecosia.atlassian.net/browse/MOB-1815)
We have noticed a fragmented approach when setting the environment.
We want to add a quick fix to the browser side, planning a proper fix in the long term.
Removed all the occurrences when the `Environment` was passed by checking the build channel.
We aligned other property injections matching the `.current` one.
Also, as 💭 oud loud, we would need to review when we pass `env` to be `.current` instead of `.production` by default as it would make more sense. That's part of the longer-term review, though.
Longer term ticket:
https://ecosia.atlassian.net/browse/MOB-1817
> Quick fix removing `Environment` setup

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/MMP/MMP.swift
[MOB-1835](https://ecosia.atlassian.net/browse/MOB-1835)
From looking at Singular's events logs, we noticed country and app version were not correct on the events (always showed the same `104.0` and `US` respectively).
- Country was added to the app device info struct on [ios-core#89](https://github.com/ecosia/ios-core/pull/89) and therefore we are passing it here now.
- Also using `AppInfo.ecosiaAppVersion` since that correctly reflects our app version, instead of `AppInfo.appVersion` which is hardcoded and shows the Firefox version we are basing on.
> MOB-1835 Add current country and ecosia app version to MMP

- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
[MOB-1914](https://ecosia.atlassian.net/browse/MOB-1914)
A temporary fix for the next release was applied on https://github.com/ecosia/ios-core/pull/106.
Updating ios-core's version so that it contains the fix.
> Mob 1914 Update Package.resolved

- Shared/en-US.lproj/Today.strings
- Shared/en.lproj/Today.strings
[MOB-1938](https://ecosia.atlassian.net/browse/MOB-1938)
It was found that one of our widgets shows "Firefox" in the english translation insted of "Ecosia.
We use [ecosify-strings.py](https://github.com/ecosia/ios-browser/blob/main/ecosify-strings.py) script to update all values once we fetch them from FF. 
Found this was due to some missing translation strings which resulted in it using the default value set inside `Shared/Strings.swift`. Added those respective strings.
Also noticed this is the case on the original repo, which for them is not a problem since the english translation is the default value 🤷 As a follow up, I have created a [technical debt](https://ecosia.atlassian.net/wiki/spaces/MOB/pages/2614362130/Technical+Debt) for checking if we can add this file to the script as well …
> [MOB-1938] Add missing english translations for shortcuts widget

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/Extensions/BrowserViewController+Ecosia.swift
- Client/Ecosia/Helpers/EcosiaInstallType.swift
- Client/Ecosia/UI/WhatsNew/DataProvider/WhatsNewLocalDataProvider.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Tests/ClientTests/Ecosia/VersionTests.swift
- Tests/ClientTests/Ecosia/WhatsNewLocalDataProviderTests.swift
- Tests/ClientTests/Mocks/MockAppVersionInfoProvider.swift
[MOB-1948](https://ecosia.atlassian.net/browse/MOB-1948)
Throughout the QA process there was an issue found as part of regression on latest fixes.
This PR reviews the logic of deciding whether of not showing the WhatsNewPage relying mostly on the EcosiaInstallType.
Scenarios tested:
- 8.3.0 -> No What's New Page shown
- 8.3.0 -> manually upgrade to 9.0.0 -> Whats New Page shown
- 9.0.0 -> run -> No Whats New Page shown 
- 9.0.0 -> rerun to 9.0.0 -> No Whats New Page shown
- 9.0.0 -> manually downgrade to 8.3.0 -> No Whats New Page shown
Will make a PR in core that removes the logic of the User
[MOB-1948]: https://ecosia.atlassian.net/browse/MOB-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-1948 Improve and fix WhatsNewPage logic

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Ecosia/Extensions/BrowserViewController+Ecosia.swift
- Client/Ecosia/Helpers/EcosiaInstallType/EcosiaInstallType+Extensions.swift
- Client/Ecosia/Helpers/EcosiaInstallType/EcosiaInstallType.swift
- Client/Ecosia/UI/WhatsNew/DataProvider/WhatsNewDataProvider.swift
- Client/Ecosia/UI/WhatsNew/DataProvider/WhatsNewLocalDataProvider.swift
- Client/Ecosia/UI/WhatsNew/WhatsNewViewModel.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Tests/ClientTests/Ecosia/EcosiaInstallTypeTests.swift
- Tests/ClientTests/Ecosia/VersionTests.swift
- Tests/ClientTests/Ecosia/WhatsNewLocalDataProviderTests.swift
- Tests/ClientTests/Frontend/Home/FirefoxHomeViewModelTests.swift
[MOB-1923]
A [bug was reported on the whats new page](https://ecosia.atlassian.net/browse/MOB-1923?focusedCommentId=83037) where it was being shown every time the NTP appears after the upgrade until the app gets killed and reopened.
Core side implementation for a refactor on the user object here: https://github.com/ecosia/ios-core/pull/119
- The main fix was removing `User.shared` from the injected dependencies and the stored property, and instead reading from `User.shared` dynamically wherever needed.
By updating the way we set given user conditions on our tests, we noticed some false-positive tests existed and that the logic on `WhatsNewLocalDataProvider.shouldShowWhatsNewPage` needed refactor: 
- Make it more compact and readable
- Include a check for empty `getData()` items on the …
> [MOB-1923] Fix whats new page user storage

- README.md
Fixes for the readme: 
clarified "current_project_version set to 0" section
normalized two heading sizes 
clarified where "IOS search signing" repo is
___
documentation
___
- Improved explanation for `CURRENT_PROJECT_VERSION` being set to `0`, enhancing understanding for local testing context.
- Fixed a typo in the description of how the build number is updated by the CI.
- Normalized heading sizes for better readability and structure in the README.
- Consolidated information about the certs and profiles management, making it easier to find the relevant repository.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Improvements in …
> Minor readme formatting and grammar fixes

- .pr_agent.toml
This reverts commits 48b80e5fc5f116db453b3869b28d0752e7794485 and 42ce95ec3833055d83123d8ecc6bdfef14112fec
https://github.com/ecosia/ios-browser/pull/655
> Revert "Codium config file - trying empty pr_commands list (#657)"

- Client/Ecosia/L10N/String.swift
- Client/Ecosia/L10N/en.lproj/Ecosia.strings
[MOB-2758]
In preparation for https://github.com/ecosia/ios-browser/pull/749, adding necessary English translations as source language.
This will trigger Transifex's integration to get the texts on other languages.
[MOB-2758]: https://ecosia.atlassian.net/browse/MOB-2758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-2758] Add source translations for climate impact CTA experiment

- Client.xcodeproj/project.pbxproj
- Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Client/Application/AppDelegate.swift
- Client/Ecosia/Helpers/EcosiaInstallType/EcosiaInstallType+Extensions.swift
- EcosiaTests/EcosiaInstallTypeTests.swift
[MOB-2773]
We want to store version on install so this can be sent to Unleash.
Using the existing `EcosiaInstallType` to know exactly when it is a fresh install and should be stored.
[MOB-2773]: https://ecosia.atlassian.net/browse/MOB-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-2773] Set version on install when fresh install type

- firefox-ios/Client.xcodeproj/project.pbxproj
[MOB-3207]
After the upgrade, the url bar reader mode button was not responsive.
First thing noticed was that this issues was caused by the page not properly updating it's reader mode status after being loaded. This resulted in it always having an unavailable state.
After lots of debugging and carefully comparing with the Firefox version, was able to pinpoint the issue to **no content script messages being received on `userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage)`**. This showed the issue was actually bigger that we initially imagined.
Luckily, the fix was not hard, since after going through the lifecycle of the content script, I noticed a number of file references missing inside `Client/Assets`. **This was apparently already …
> [MOB-3207] Add missing references to content script assets

- firefox-ios/Client/Frontend/TrackingProtection/TrackingProtectionViewController.swift
[MOB-3206]
One of the things added by Firefox was a nice header to the privacy screen.
For now, we remove the header since it is not Ecosia branded (see comments on the ticket).
[MOB-3206]: https://ecosia.atlassian.net/browse/MOB-3206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-3206] Remove Firefox branded header view from Privacy screen
